version: "3"

services:
  postgresdb:
    container_name: devhackdb
    image: postgres:13
    environment:
      POSTGRES_USER: devhack
      POSTGRES_PASSWORD: devhack123
      POSTGRES_DB: devhackdb
    ports:
      - 5432:5432
    networks:
      - default
    expose:
      - "5432"
    volumes:
      - ./schemas/local-data/db/devhackdb:/var/lib/postgresql/data
  mysqldb:
    container_name: devhackdbmysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devhackdb
      MYSQL_USER: devhack
      MYSQL_PASSWORD: devhack123
    ports:
      - 3306:3306
    networks:
      - default
    expose:
      - "3306"
    volumes:
      - ./schemas/local-data/db/devhackmysql:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    volumes:
      - ./schemas/local-data/db/mongodb:/data/db
  gateway:
    build:
      context: gateway
      dockerfile: docker/Dockerfile
    ports:
      - 8084:8080
    environment:
      MYSQL_DATABASE_URL: devhack:devhack123@tcp(host.docker.internal:3306)/devhackdb
    depends_on:
      - mysqldb
  product:
    build:
      context: product
      dockerfile: docker/Dockerfile
    ports:
      - 8085:8080
    environment:
      POSTGRESQL_DATABASE_URL: postgresql://devhack:devhack123@devhackdb:5432/devhackdb?sslmode=disable
    depends_on:
      - postgresdb
