version: "3"

services:
  db:
    container_name: devhackdb
    image: postgres:13
    environment:
      POSTGRES_USER: devhack
      POSTGRES_PASSWORD: devhack123
      POSTGRES_DB: devhackdb
    ports:
      - 5432:5432
    networks:
      - default
    expose:
      - "5432"
    volumes:
      - ./schemas/local-data/db/devhackdb:/var/lib/postgresql/data
  auth:
    build:
      context: auth
      dockerfile: docker/Dockerfile
    ports:
      - 8084:8080
    environment:
      DATABASE_URL: postgresql://devhack:devhack123@devhackdb:5432/devhackdb?sslmode=disable
      SECRET_KEY: supersecretkey123
    depends_on:
      - db
  ecom:
    build:
      context: ecom
      dockerfile: docker/Dockerfile
    ports:
      - 8085:8080
    environment:
      DATABASE_URL: postgresql://devhack:devhack123@devhackdb:5432/devhackdb?sslmode=disable
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - db
